#Site settings

plugins:
  - jekyll-sitemap

markdown: kramdown

title: Always Free Resumé Builder
description: >-
  blah blah

# this is temporary while I develop on GH-pages. Will move to proper url later)
baseurl: "/alwaysfreeresume"
url: "https://heirofnorton.github.io"

# defaults:
#  -
#    scope:
#      path: ""
#        values:
#        layout: default

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - oldpages/
