#Site settings

plugins:
  - jekyll-sitemap

markdown: kramdown

title: Always Free Resumé Builder
description: >-
  blah blah

# this is temporary while I develop on GH-pages. Will move to proper url later)
baseurl: "/alwaysfreeresume"
url: "https://heirofnorton.github.io"

# defaults:
#  -
#    scope:
#      path: ""
#        values:
#        layout: default

navtitle:
  standard: Standard
  student: Student
  functional: Functional
  entrylevel: Entry Level

navlength:
  standard: 6
  student: 6
  entrylevel: 5
  functinoal: 5

nav:
  standard:
    - Objective
    - Skills
    - Experience
    - Education
    - Extras
  student:
    - Objective
    - Skills
    - Education
    - Projects
    - Work Experience
    - Extras
  entrylevel:
    - Objective
    - Skills
    - Education
    - Experience
    - Extras
  functional:
    - Objective
    - Skills
    - Experience
    - Education
    - Extras

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

