#Site settings

plugins:
  - jekyll-sitemap

markdown: kramdown

title: Always Free Resumé Builder
description: >-
  blah blah
baseurl: ""
url: ""

# defaults:
#  -
#    scope:
#      path: ""
#        values:
#        layout: default

nav:
  standard:
    - Objective
    - Skills
    - Experience
    - Education
    - Extras
  student:
    - Objective
    - Skills
    - Education
    - Projects
    - Work Experience
    - Extras
  Entry Level:
    - Objective
    - Skills
    - Education
    - Experience
    - Extras
  Functional:
    - Objective
    - Skills
    - Experience
    - Education
    - Extras

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

